name: flutter_soft_keyboard
description: "This Flutter package is a virtual keyboard widget that can be implemented using a 2D array."
version: 1.2.0
homepage: "https://aqoong.site/"
repository: "https://github.com/aqoong/flutter_soft_keyboard"
issue_tracker: "https://github.com/aqoong/flutter_soft_keyboard/issues"

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  size_tailored_text: ^1.0.8
  ripple_container: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  aqlinter: ^1.0.2

license: MIT